#!/usr/bin/env bash
# deploy.sh – End-to-end deployment helper for the AWS Bedrock RAG system.
#
# Usage:
#   ./scripts/deploy.sh                          # prompts for profile
#   AWS_PROFILE=myprofile ./scripts/deploy.sh    # non-interactive
#   ./scripts/deploy.sh --destroy                # tear down all resources

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$REPO_ROOT/terraform"
BUILD_DIR="$REPO_ROOT/build"

# ── Colour helpers ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

DESTROY=false
for arg in "$@"; do
  [[ "$arg" == "--destroy" ]] && DESTROY=true
done

# ── Prerequisite checks ───────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   AWS Bedrock RAG System – Deployment Script         ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

for cmd in terraform python3 aws pip3; do
  if ! command -v "$cmd" &>/dev/null; then
    error "$cmd is not installed or not in PATH."
    exit 1
  fi
done
success "All required tools found."

# ── Install Python dependencies (needed for create_opensearch_index.py) ──────
info "Installing Python dependencies …"
pip3 install -r "$REPO_ROOT/requirements.txt" --quiet
success "Python dependencies installed."

# ── Resolve AWS profile ───────────────────────────────────────────────────────
if [[ -z "${AWS_PROFILE:-}" ]]; then
  read -rp "Enter AWS profile name [default]: " AWS_PROFILE
  AWS_PROFILE="${AWS_PROFILE:-default}"
fi
info "AWS profile: $AWS_PROFILE"

if ! aws sts get-caller-identity --profile "$AWS_PROFILE" --output text &>/dev/null; then
  error "AWS authentication failed for profile '$AWS_PROFILE'."
  error "Run: aws configure --profile $AWS_PROFILE"
  exit 1
fi
IDENTITY=$(aws sts get-caller-identity --profile "$AWS_PROFILE" --output text --query 'Arn')
success "Authenticated as: $IDENTITY"

# ── Create terraform.tfvars if missing ────────────────────────────────────────
TFVARS="$TERRAFORM_DIR/terraform.tfvars"
if [[ ! -f "$TFVARS" ]]; then
  info "Creating terraform.tfvars …"
  cat > "$TFVARS" <<EOF
# Auto-generated by deploy.sh – safe to edit.
aws_profile = "$AWS_PROFILE"
EOF
  success "Created $TFVARS"
else
  info "terraform.tfvars already exists – skipping."
fi

# ── Prepare build directory ───────────────────────────────────────────────────
mkdir -p "$BUILD_DIR"

# ── Terraform init ────────────────────────────────────────────────────────────
info "Initialising Terraform …"
cd "$TERRAFORM_DIR"
terraform init -upgrade

# ── Destroy path ─────────────────────────────────────────────────────────────
if [[ "$DESTROY" == "true" ]]; then
  warn "DESTROY mode activated.  This will delete ALL resources."
  read -rp "Type 'yes' to confirm: " CONFIRM
  if [[ "$CONFIRM" != "yes" ]]; then
    info "Cancelled."
    exit 0
  fi
  terraform destroy -var="aws_profile=$AWS_PROFILE" -auto-approve
  success "All resources destroyed."
  exit 0
fi

# ── Plan ──────────────────────────────────────────────────────────────────────
info "Planning deployment …"
PLAN_FILE="$BUILD_DIR/tfplan"
terraform plan -var="aws_profile=$AWS_PROFILE" -out="$PLAN_FILE"

echo ""
read -rp "Apply this plan? (yes/no): " CONFIRM
if [[ "$CONFIRM" != "yes" ]]; then
  info "Deployment cancelled."
  exit 0
fi

# ── Apply ─────────────────────────────────────────────────────────────────────
info "Applying deployment …"
terraform apply "$PLAN_FILE"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   Deployment complete!                               ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
info "Terraform outputs:"
terraform output
echo ""

KB_ID=$(terraform output -raw knowledge_base_id 2>/dev/null || echo "")
CONFIG_SECRET=$(terraform output -raw rag_config_secret_name 2>/dev/null || echo "")
BEDROCK_SECRET=$(terraform output -raw bedrock_config_secret_name 2>/dev/null || echo "")
REGION=$(terraform output -raw aws_region 2>/dev/null || echo "us-east-1")

echo "Next steps:"
echo ""
echo "  1. Upload documents to the S3 bucket:"
echo "     python3 src/ingest.py ./your-docs/ \\"
echo "       --secret-name $CONFIG_SECRET \\"
echo "       --profile $AWS_PROFILE --region $REGION --wait"
echo ""
echo "  2. Query the knowledge base:"
echo "     python3 src/query.py 'Your question here' \\"
echo "       --config-secret $CONFIG_SECRET \\"
echo "       --bedrock-secret $BEDROCK_SECRET \\"
echo "       --profile $AWS_PROFILE --region $REGION"
echo ""
echo "  3. Invoke via Lambda function URL (SigV4 signed):"
echo "     curl -X POST \$(terraform -chdir=terraform output -raw lambda_function_url) \\"
echo "       --aws-sigv4 'aws:amz:$REGION:lambda' \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"query\": \"Your question\"}'"
echo ""
